#!/bin/bash
echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"
# Display listening ports as well as the PID and program name
sudo netstat -tunlp | grep 'LISTEN'

